load("@buildifier_prebuilt//:rules.bzl", "buildifier", "buildifier_test")
load("@rules_multirun//:defs.bzl", "command", "multirun")
load("@rules_tf//tf:defs.bzl", "tf_fmt")

buildifier(
    name = "lint_fix_bzl",
    exclude_patterns = ["./.git/*"],
    lint_mode = "fix",
    mode = "fix",
    tags = ["manual"],
)

buildifier_test(
    name = "lint",
    exclude_patterns = ["./.git/*"],
    lint_mode = "warn",
    mode = "diff",
    no_sandbox = True,
    workspace = "//:MODULE.bazel",
)

tf_fmt(
    name = "lint_fix_tf",
    srcs = glob(
        [
            "**/*.tf",
            "**/*.tpl",
        ],
    ),
    fix = True,
    tags = ["manual"],
)

command(
    name = "lint_fix_bazel",
    command = "//:lint_fix_bzl",
)

command(
    name = "lint_fix_terraform",
    command = "//:lint_fix_tf",
)

multirun(
    name = "lint_fix_all",
    commands = [
        "lint_fix_bazel",
        "lint_fix_terraform",
    ],
    visibility = ["//visibility:public"],
)
