name: Pull requests

on:
  pull_request:
    branches:
    - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "${{ vars.BAZELISK_IMAGE }}"
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        persist-credentials: false
    - name: test
      run: |
        bazel test //...
